name: Test Steam API

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: pip install steam[client]
      - name: Test Steam client connection
        env:
          STEAM_USER: ${{ secrets.STEAM_USER }}
          STEAM_PASS: ${{ secrets.STEAM_PASS }}
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
        run: python test_api.py
